// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Response> performNtlmRequest({
  required Method method,
  required String url,
  required List<(String, String)> headers,
}) => RustLib.instance.api.crateApiPerformNtlmRequest(
  method: method,
  url: url,
  headers: headers,
);

enum Method { get_ }

class Response {
  final int status;
  final String body;

  const Response({required this.status, required this.body});

  @override
  int get hashCode => status.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Response &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          body == other.body;
}
