// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> performNtlmRequest({
  required Method method,
  required String url,
  required List<(String, String)> headers,
}) => RustLib.instance.api.crateApiPerformNtlmRequest(
  method: method,
  url: url,
  headers: headers,
);

enum Method { get_ }
